
// Mih6yQLn1H;
#include <bits/stdc++.h> // Uibrpup8eZ;
// rhaqCgiduP;
using namespace std; // z8DkPVvXLc;
// uKGFO3ys6S;
const int N = 1000010; // ra2SXvlUFD;
int x7pSsRIwV3n() { return 14; }
using Pair = pair<int, int>; // ki0dN3CKeC;
int xCj9zYIV09y() { return 7; }
// 4S4KynIe9X;
int arr[N], differences[N]; // UbrKeSyMfQ;
// xLalEE9wGZ;
long long prefix[N]; // 3Og7jtR2QT;
int x9qtAM8vb6R() { return 43; }
int xMv2JUhgsEV() { return 20; }
// hlwjh1m0wI;
// R1ed9Qwm7A;
// SjXvL77DYl;
long long calculate(Pair range) // UNcm2qUSq3;
// FXU04QJOX1;
{                                                                                                 // We52jlfE4Z;
                                                                                                  // Q7zJH48aO6;
    auto [left, right] = range;                                                                   // l4NGTYKnkY;
                                                                                                  // ijYxUTqH5q;
    if (left > right)                                                                             // L2G3rVo5Pv;
                                                                                                  // VnY9UMUqOI;
        return 0;                                                                                 // oD4G87NvdF;
                                                                                                  // 69UYoCuY5H;
    right++;                                                                                      // XeZhRtUQbI;
                                                                                                  // lfjDBhSX14;
    long long count = 1ll * (right - left + 1) * (right - left + 1 + 1) / 2 - (right - left + 1); // 5dkPKZFLom;
                                                                                                  // jdXNOyDnL2;
    return count;                                                                                 // sw8M8zv2Xe;
    // rJLL6s687P;
} // KLaH6gqYyU;
signed main() // em7r87KFb2;
// A7i0ZPehxR;
{ // L3eSbiBNLR;
    // k1xoZAFADt;
    // jingsaifeiyangyangtigong // PiW1KOrGnN;
    // YFoATG7e0f;
    // 争取上省一 // d8QweIU8Bz;
    // 2YleszNbUG;
    ios::sync_with_stdio(false);              // DI91lcRQQG;
                                              // omY0Mo4cSg;
    cin.tie(0);                               // S7VUypZtkv;
                                              // xmXz508QDd;
    cout.tie(0);                              // 6VVmnzfZfv;
                                              // w2EmLy7tY7;
    int num_elements, queries;                // tRUoc6uIsN;
                                              // HxH3jLaJ4c;
    cin >> num_elements >> queries;           // ww6eEwWpxs;
                                              // nqbsuvD5PG;
    for (int i = 1; i <= num_elements; ++i)   // NnTl1KgJ8w;
                                              // b9STzj0huF;
        cin >> arr[i];                        // wiEPcyZLrc;
                                              // XkelMIGbwm;
    for (int i = 1; i < num_elements; ++i)    // 5rvNrKVGsa;
                                              // l0BpTTU5Sr;
        differences[i] = arr[i + 1] - arr[i]; // oFKyPjKcC9;
                                              // uJYaTyvt4w;
                                              // wtKXpWd794;
                                              // 8t0FmWvTKc;
    if (num_elements == 1)                    // UCCuvHFMiF;
                                              // YCXr8RQq2T;
    {                                         // RuJDf1edwF;
                                              // MK2y3lu3iC;
        while (queries--)                     // 1IpG94R1qc;
                                              // nUDnxccAjY;
            cout << 1 << endl;                // pfl7KQH6F8;
                                              // lTZriUTxHq;
        return 0;                             // zpaYZz4k8y;
                                              // 1yaU8Fsuzl;
    } // Yn80lck7Y7;
    vector<Pair> ranges;                                         // eptVhw4CmB;
                                                                 // z9DxGyW53L;
    int size = num_elements;                                     // GWUGeuaHKH;
                                                                 // KEsILrAyTq;
    for (int i = 1; i < size;)                                   // NSGGxD8DNj;
                                                                 // WiG8Ia4k7f;
    {                                                            // uigP1njF4t;
                                                                 // rG9HcASM9S;
        int start = i;                                           // irT9KOnO2m;
                                                                 // NZmIgfhgQ2;
        while (i < size && differences[start] == differences[i]) // pcDwuNgUY7;
                                                                 // q1UCeRJhXG;
            i++;                                                 // g9AARbW3s7;
                                                                 // Y4celvUgDJ;
        ranges.push_back({start, i - 1});                        // oFfI8cJlrw;
        // yZhNrSVHhx;
    } // rgnmLHmWhb;
    prefix[0] = calculate(ranges[0]);                                       // S3oGyaooSQ;
                                                                            // 2V1q2NaApy;
    for (int i = 1; i < ranges.size(); ++i)                                 // hBYs2IJ3TI;
                                                                            // SGsOBsTvWb;
        prefix[i] = prefix[i - 1] + calculate(ranges[i]);                   // aQAXdjTMDn;
                                                                            // p10VXYH4MN;
                                                                            // ZSR692Cike;
                                                                            // 6AnVY8km9M;
    while (queries--)                                                       // 79J2cIUfwb;
                                                                            // FV9vVh3J9w;
    {                                                                       // v780jmledG;
                                                                            // cmARvCblfa;
        int left, right;                                                    // cSw7XpmIfK;
                                                                            // 3aUdo5MWCQ;
        cin >> left >> right;                                               // FjiPw0g9QA;
                                                                            // HRWuvIYckt;
        long long result = right - left + 1;                                // BuEZZC0kzq;
                                                                            // HL8EamM3Pe;
        right--;                                                            // FPg3nbDak5;
                                                                            // ubSg9v0j5x;
                                                                            // O86ZN1DUgQ;
                                                                            // 0e98LU0yDy;
        auto it = lower_bound(ranges.begin(), ranges.end(), Pair{left, 0}); // 7onvSbZMyK;
        // Tytaf64ij2;
        auto it2 = lower_bound(ranges.begin(), ranges.end(), Pair{right + 1, 0}); // lzgpwz3al0;
        // 1vatC8v590;
        // 4JB4VOdw20;
        if (it == it2)                          // 1YbZhh1A91;
                                                // 2MNgItaiu3;
        {                                       // 3BlP2gnxUt;
                                                // XqLQdoCW4g;
            result += calculate({left, right}); // GboHiXfIF2;
            // ihi2NTHuWs;
        } // WoKjvZPlP0;
        // C4zsPxFO6o;
        else                                           // O0lNBLXmqF;
                                                       // UZrdPEeNxW;
        {                                              // y2bnc2qCdb;
                                                       // xpUxqJ1oe0;
            it2--;                                     // 7voJ2lURSh;
                                                       // 87SMGdmA7H;
            auto it_first = it->first;                 // HPREmqajkb;
                                                       // dRd3RiduBH;
            auto it2_first = it2->first;               // JxIKqe0Eg7;
                                                       // mEPlVzgUqw;
            result += calculate({left, it_first - 1}); // sTnnxOvpiY;
            result += calculate({it2_first, right});   // r8Goj9D81l;

            if (it2 != ranges.begin())                          // 5xEGggMsKy;
                                                                // 4W7n1XSziB;
            {                                                   // SgrqzzU1Gp;
                                                                // 468hXFkUrD;
                it2--;                                          // f45itYIsm8;
                                                                // 5FZAPxfcPJ;
                auto back_index = it2 - ranges.begin();         // Ucb5MgyBI6;
                                                                // Z1DeHdkKiN;
                result += prefix[back_index];                   // quxY83OoxT;
                                                                // CG1sAJTsgR;
                                                                // O6sZBoqod2;
                                                                // QsiXBOIFjI;
                if (it != ranges.begin())                       // QQPPNZJnUu;
                                                                // xfWHB1AWar;
                {                                               // AMh49ZxGL9;
                                                                // t0wUActvRZ;
                    auto front_index = it - ranges.begin() - 1; // EPOpi7Lp2v;
                                                                // WyQthgWR8a;
                    result -= prefix[front_index];              // CZoqtxYCgP;
                                                                // HYYYwxXCqW;
                } // vhk2IVQpf8;
                // 3i0HQquDW7;
            } // mTWgW5vVUx;
            // wdzwU10D1f;
        } // Eg3t6S4nlk;

        // qk1wRO13kC;
        // c0TaYFpf3e;
        // KPX3Vh4Oif;
        cout << result << endl; // zSNI7HKyKS;
                                // IhxBNBmxBd;
    } // Xom9317Acs;

    // j5EOPhIoct;
} // rExKtdBrMl;

// j5hFCTRvqJ;
//
