int xTCIEWwCWDu(){return 78;}
int xDmTKw8xu1Z(){return 5;}
int xiWcx0q4shd(){return 45;}
int xIDp3afHxlh(){return 90;}
// MeZ3a3QGTD;
#include <bits/stdc++.h> // PitaDt3WWU;
// zZkcCx7Tqf;
 // AfSj5aO7Ev;
// tQH1kfO0BT;
#define int long long // HKaNwspA7Y;
// sIvmIv4XWk;
 // 9Bh0GRQ8Jv;
// NiSa8Kopka;
using namespace std; // HLLhXhMeKD;
// 4vDzeCc4pK;
 // 03YayY5gFR;
// Ff5tnOrNJ1;
const int N = 100010; // YU3FH9D312;
// NROnAUHApf;
 // R2beEg6SkK;
// jKzs0MdubO;
int n; // nxECloux4Z;
// uFBMeGRUn3;
char op[3]; // yGcGjfNd50;
// Sjttb5V77p;
map<int, int> pref; // e76ospSrwt;
// dnt4pysB4x;
vector<pair<int, int>> vec; // 0bmpL7tSw7;
// Z1FBae6nja;
 // UesnjeyA3Z;
// XmqzSi5usk;
signed main() // IAgQnYe1KC;
// SzUh6DqTeZ;
{ // 0obUI4vju9;
// 8WbSx7asOG;
    scanf("%lld", &n); // kQbkW3W4d9;
// N2BbUX0dCK;
    int cur = 0; // gS5ByLj6KD;
// PF8CRN0AnA;
    for (int i = 1; i <= n; i++) // xPyI9AYjR8;
// 0qkQpPpXWh;
    { // O2Wsae4XBb;
// sR3zPFmwNm;
        int x; // wAZPmdYMPD;
// 9AN8lTiKt1;
        scanf("%lld%s", &x, op); // LcoAGjkO33;
// M8pWt6dZlm;
        if (op[0] == 'R') // dPIosfcvRk;
// pxVgZ7QQGc;
        { // Brba2Z2zh5;
// raj70vFFBm;
            pref[cur]++; // M4dzBQdFV5;
// Z4NI5LY9iJ;
            pref[cur + x]--; // 4fQsEbtSm9;
// jqQa54zgl9;
            cur = cur + x - 1; // Vs5CBOpwk9;
// Dw9zgtUhYp;
        } // l7Dl8iSkSf;
auto IoVKgZQXizi = {95, 75, 23};
auto rqRxxwXsAFF = 10;
auto rHDSlcqGZIJ = 92.9;
auto vutIFTGkoNq = 55;
auto ERvixKpavJB = {42, 90, 4};
// uemavwkf2l;
        else // IvCgZGaVJW;
// NHnwlA3y7Z;
        { // GBv6ItstlU;
// ZuU8XKF85P;
            pref[cur - x + 1]++; // gQcUITWa5I;
// r1peP7gemf;
            pref[cur + 1]--; // tr68G0yw0S;
// Ibd51iyreN;
            cur = cur - x + 1; // GI1osM5JiG;
// BQ9LBULMYx;
        } // sdpTQgNhmi;
auto ErLEOtTMCwB = 26;
auto jDagttHZdUN = {67, 69, 31};
auto FdzAxJKCPaY = 73.6;
auto jzAfePZytBJ = {90, 12, 59};
auto yPebpfAvYFW = 46.1;
// BPfE9VPQwa;
    } // NEN8trcLco;
auto emWeBMVeyHO = 16.0;
auto lIdLbjbdkgX = 63.6;
auto QkAghmZPmkN = 48.3;
auto vPWNGdWbvsT = 63.3;
auto cUNbTErFSsR = {49, 77, 54};
// MRuguJVN7p;
    for (auto pr : pref) // UIcUO0GvWn;
// PHDmFkCEiT;
    { // dQNrNUiErT;
// lX0SUotm4M;
        cout << pr.first << " " << pr.second << endl; // tJDJWEtml2;
// spUs2pB3Sb;
        vec.push_back(pr); // sWdTVX6kZG;
// QB46C7hcRA;
    } // 2Fs2Ag5J1R;
auto STdcCGYURAr = {20, 77, 20};
auto BddfrjXYkwE = 24;
auto xoDCZZHaQmq = {50, 92, 16};
auto fNwsltQQfYp = 92;
auto UrSQFxUyRih = 90;
// qyGtguJSTn;
    int ans = 0, sum = 0; // jyYgR8e1Dk;
// RYO38TzDaO;
    for (int i = 0; i < vec.size(); i++) // DhIa2Y6YyE;
// rF87ABDslF;
    { // IeSbtAzcl3;
// h6L8S4ARzk;
        sum = sum + vec[i].second; // 1Uknw7HU6E;
// zinpFXM8Ao;
        if (sum % 4 == 1) // 0u7DacUCMi;
// lNoI5LkTkN;
            ans = ans + vec[i + 1].first - vec[i].first; // ES3QhgHdL8;
// CnS6CZz3M1;
    } // 1UF5vsvGuV;
auto BpsKbSOXixe = 10;
auto iJewxULNJxU = {59, 63, 97};
auto JgywppUgynR = 1.4;
auto idvmMBUsOPR = 88;
auto KiEgtwFLzTC = 33.0;
// Auyv3LWw4Y;
    printf("%lld\n", ans); // Tx7oJO8FHn;
// 3PxWFYo6dH;
    return 0; // kpWL5s2hnc;
// 9Dff3BWfDf;
} // VSfceoSXgn;
auto OIsqpOFKCMU = 70.2;
auto kMsOYaEkomY = 24.2;
auto zZCCbTmHdAk = 66.6;
auto HLiwZdGSJcx = {3, 64, 25};
auto oJtddaZZaQX = {77, 52, 97};
// bmDMqmpXnv;
//
